### ISSUE TITLE
请问安装环境是什么呢？报错AttributeError: 'ImageDraw' object has no attribute 'rounded_rectangle'

### ISSUE THREAD

**Issue by zimengxueying** [QPT-Family/QGUI#9]
运行给的demo代码报错，如下图，是版本的问题么？

![QQ图片20220314193305](https://user-images.githubusercontent.com/32453573/158163756-a3cd9cbf-be0a-421c-ac8b-fa164d59e00f.png)

**Comment by zimengxueying** [comment]
> 运行给的demo代码报错，如下图，是版本的问题么？
> 
> ![QQ图片20220314193305](https://user-images.githubusercontent.com/32453573/158163756-a3cd9cbf-be0a-421c-ac8b-fa164d59e00f.png)

不好意思已解决，是我的Pillow版本不对应，至少是8.2.0

**Comment by GT-ZhangAcer** [comment]
https://github.com/QPT-Family/QGUI/actions/runs/1980307803
下个版本将约束Pillow版本

**Comment by zimengxueying** [comment]
> 

你好，小白想请问下，这个能打包成exe的形式嘛？

**Comment by GT-ZhangAcer** [comment]
支持Pyinstaller、cxfreeze等打包工具，也可以使用QPT-Family的QPT打包 https://github.com/QPT-Family/QPT

**Comment by zimengxueying** [comment]
> 

感谢！！

**Comment by GT-ZhangAcer** [comment]
QPT打包可参考 https://github.com/AP-Kai/Paint-Master 这个QGUI+QPT的案例，还是比较简单的
